import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        md: "480px",
      },
      colors: {
        "polks-brand": "#25343F",
        "polks-smile": "#FF6B4A",
        "polks-smile-soft": "#FFE1D8",
        "polks-point": "#F6B84B",
        "polks-point-soft": "#FFF3D1",
        "polks-bg": "#F6F8FA",
        "polks-surface": "#EEF2F4",
        "polks-border": "#DDE3E7",
        "polks-text": "#17212A",
        "polks-muted": "#66737D",
        "polks-success": "#38A169",
        "polks-error": "#E04F4F",
        "on-tertiary-container": "#d3d1ff",
        "surface-container-low": "#EEF2F4",
        "on-tertiary-fixed": "#0f0069",
        "on-primary-fixed": "#001551",
        "error-container": "#ffdad6",
        "surface-container": "#ededf9",
        "on-secondary-fixed": "#131b2e",
        outline: "#747686",
        "surface-container-highest": "#e2e1ed",
        "on-background": "#1a1b23",
        "on-surface": "#1a1b23",
        "inverse-on-surface": "#f0f0fb",
        "tertiary-container": "#4b41e1",
        "outline-variant": "#DDE3E7",
        "surface-bright": "#F6F8FA",
        "primary-container": "#EEF2F4",
        "tertiary-fixed": "#e2dfff",
        surface: "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "secondary-fixed": "#dae2fd",
        "surface-container-high": "#EEF2F4",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "inverse-primary": "#b7c4ff",
        error: "#ba1a1a",
        "on-secondary-container": "#5c647a",
        "secondary-container": "#dae2fd",
        "on-surface-variant": "#66737D",
        "surface-tint": "#FF6B4A",
        "surface-variant": "#EEF2F4",
        "on-primary-container": "#25343F",
        primary: "#25343F",
        "primary-fixed": "#ffffff",
        "inverse-surface": "#2e3039",
        tertiary: "#311fca",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        success: "#16a34a",
        "success-container": "#dcfce7",
        "on-success-container": "#166534",
        background: "#F6F8FA",
        "tertiary-fixed-dim": "#c3c0ff",
        secondary: "#565e74",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#0039b5",
        "primary-fixed-dim": "#b7c4ff",
        "deep-navy": "#25343F",
        gold: "#F6B84B",
        "soft-gold": "#FFF3D1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        "margin-mobile": "16px",
        lg: "24px",
        gutter: "24px",
        xl: "32px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "app-name": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        body: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "card-title": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "label-xs": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "page-title": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        caption: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "section-title": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-semibold": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
      },
      fontSize: {
        "app-name": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "card-title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "12px", fontWeight: "700" }],
        "page-title": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "section-title": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-semibold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
