-- AlterTable
ALTER TABLE "loyalty_config" ADD COLUMN     "rateBronze" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "rateGold" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN     "ratePlatinum" INTEGER NOT NULL DEFAULT 850,
ADD COLUMN     "rateSilver" INTEGER NOT NULL DEFAULT 950,
ADD COLUMN     "tierGoldMin" INTEGER NOT NULL DEFAULT 1000000,
ADD COLUMN     "tierPlatinumMin" INTEGER NOT NULL DEFAULT 1500000,
ADD COLUMN     "tierSilverMin" INTEGER NOT NULL DEFAULT 500000;
