import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BarChart3,
  Bell,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleDollarSign,
  CloudCheck,
  Coffee,
  Copy,
  CreditCard,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  Filter,
  Gift,
  History,
  Home,
  Inbox,
  LayoutDashboard,
  Lock,
  LogOut,
  LogIn,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  Pencil,
  Phone,
  PlaneTakeoff,
  Plus,
  PlusCircle,
  QrCode,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Star,
  Store,
  Tag,
  Terminal,
  Ticket,
  Trash2,
  TriangleAlert,
  Trophy,
  User,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  Webhook,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  account_balance_wallet: Wallet,
  add: Plus,
  add_circle: PlusCircle,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  calendar_month: CalendarDays,
  campaign: Megaphone,
  card_giftcard: Gift,
  card_membership: CreditCard,
  badge: CreditCard,
  check_circle: CheckCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cloud_done: CloudCheck,
  coffee_maker: Coffee,
  content_copy: Copy,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  expand_more: ChevronDown,
  filter_list: Filter,
  flight_takeoff: PlaneTakeoff,
  gpp_maybe: ShieldAlert,
  group: Users,
  history: History,
  home: Home,
  inbox: Inbox,
  local_activity: Ticket,
  local_mall: ShoppingBag,
  shopping_bag: ShoppingBag,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  login: LogIn,
  call: Phone,
  mail: Mail,
  menu: Menu,
  military_tech: Medal,
  more_vert: EllipsisVertical,
  notifications: Bell,
  person: User,
  person_add: UserPlus,
  qr_code: QrCode,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  restaurant: Utensils,
  search: Search,
  settings: Settings,
  stars: Star,
  store: Store,
  storefront: Store,
  sync: RefreshCw,
  sync_alt: RefreshCw,
  document_scanner: ScanLine,
  redeem: Gift,
  terminal: Terminal,
  tune: SlidersHorizontal,
  verified_user: ShieldCheck,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  webhook: Webhook,
  workspace_premium: Trophy,
  // Extra aliases kept for parity with common Material Symbols usage
  check: Check,
  delete: Trash2,
  paid: CircleDollarSign,
  sell: Tag,
  verified: BadgeCheck,
  visibility: Eye,
};

export function Icon({
  name,
  className,
  fill = false,
  ...props
}: { name: string; className?: string; fill?: boolean } & Omit<React.SVGProps<SVGSVGElement>, "fill">) {
  const Cmp = MAP[name];
  if (!Cmp) {
    if (process.env.NODE_ENV !== "production") console.warn(`Icon: unmapped "${name}"`);
    return null;
  }
  return <Cmp className={className} {...(fill ? { fill: "currentColor" } : {})} {...props} />;
}
